# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
parameters:
    unsignedPipelineResource: null
    unsignedArtifactName: null
    signedArtifactName: null
    channel: null

jobs:
    - job: ${{ parameters.signedArtifactName }}
      pool:
          vmImage: windows-2019
      steps:
          - template: ../../install-node-prerequisites.yaml

          - task: DownloadPipelineArtifact@2
            inputs:
                source: 'specific'
                runVersion: 'specific'
                project: $(resources.pipeline.${{ parameters.unsignedPipelineResource }}.projectID)
                pipeline: $(resources.pipeline.${{ parameters.unsignedPipelineResource }}.pipelineID)
                runId: $(resources.pipeline.${{ parameters.unsignedPipelineResource }}.runID)
                artifact: ${{ parameters.unsignedArtifactName }}
                path: '$(System.DefaultWorkingDirectory)/drop/electron/unified-${{ parameters.channel }}'

          - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
            displayName: 'ESRP: Sign unpacked binaries'
            inputs:
                ConnectedServiceName: 'ESRP Code Signing'
                FolderPath: '$(System.DefaultWorkingDirectory)/drop/electron/unified-${{ parameters.channel }}'
                Pattern: '*.exe, *.dll'
                signConfigType: inlineSignParams
                inlineOperation: |
                    [
                        {
                        "keyCode": "CP-231522",
                        "operationSetCode": "SigntoolSign",
                        "parameters": [
                            {
                            "parameterName": "OpusName",
                            "parameterValue": "Microsoft"
                            },
                            {
                            "parameterName": "OpusInfo",
                            "parameterValue": "http://www.microsoft.com"
                            },
                            {
                            "parameterName": "PageHash",
                            "parameterValue": "/NPH"
                            },
                            {
                            "parameterName": "FileDigest",
                            "parameterValue": "/fd sha256"
                            },
                            {
                            "parameterName": "TimeStamp",
                            "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                            }
                        ],
                        "toolName": "signtool.exe",
                        "toolVersion": "6.2.9304.0"
                        }
                    ]

          - script: yarn pack:unified:${{ parameters.channel }}
            displayName: yarn pack:unified:${{ parameters.channel }}

          - task: CopyFiles@2
            displayName: 'copy the packed installers for signing'
            inputs:
                SourceFolder: '$(System.DefaultWorkingDirectory)/drop/electron/unified-${{ parameters.channel }}/packed'
                contents: |
                    latest*.yml
                    Accessibility?Insights?for?Android*.*
                TargetFolder: '$(System.DefaultWorkingDirectory)/signing-in-progress/${{ parameters.signedArtifactName }}/packed'

          - template: sign-release-package.yaml
            parameters:
                filePattern: '*.exe'
                platform: windows
                signedArtifactName: ${{ parameters.signedArtifactName }}
                inlineSignParams: |
                    [
                        {
                        "keyCode": "CP-230012",
                        "operationSetCode": "SigntoolSign",
                        "parameters": [
                            {
                            "parameterName": "OpusName",
                            "parameterValue": "Microsoft"
                            },
                            {
                            "parameterName": "OpusInfo",
                            "parameterValue": "http://www.microsoft.com"
                            },
                            {
                            "parameterName": "PageHash",
                            "parameterValue": "/NPH"
                            },
                            {
                            "parameterName": "FileDigest",
                            "parameterValue": "/fd sha256"
                            },
                            {
                            "parameterName": "TimeStamp",
                            "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                            }
                        ],
                        "toolName": "signtool.exe",
                        "toolVersion": "6.2.9304.0"
                        }
                    ]

          - task: securedevelopmentteam.vss-secure-development-tools.build-task-codesignvalidation.CodeSign@1
            displayName: codesign validation
            inputs:
                Path: $(System.DefaultWorkingDirectory)
                Targets: +:f|signing-in-progress/**.exe;+:f|drop/electron/unified-${{ parameters.channel }}/packed/win-unpacked/**.dll;drop/electron/unified-${{ parameters.channel }}/packed/win-unpacked/**.exe;
                ExcludePassesFromLog: false
