# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
schedules:
    - cron: '0 9 * * 1-5'
      displayName: Weekdays at 9AM UTC (2AM PDT)
      branches:
          include:
              - main
trigger:
    - unified-e2e-reliability/*
pr:
    paths:
        include:
            - src/tests/electron/

jobs:
    - template: ./unified-e2e-job-per-environment.yaml
      parameters: { jobNameSuffix: _1 }

    - template: ./unified-e2e-job-per-environment.yaml
      parameters: { jobNameSuffix: _2 }

    - template: ./unified-e2e-job-per-environment.yaml
      parameters: { jobNameSuffix: _3 }

    - template: ./unified-e2e-job-per-environment.yaml
      parameters: { jobNameSuffix: _4 }

    - template: ./unified-e2e-job-per-environment.yaml
      parameters: { jobNameSuffix: _5 }
